# Site
repository: yht0827/resume-theme
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2
update_date: 2023.01.25

# Personal info
name: 양희태
title: Software Engineer
email: yangheetae0827@naver.com
# email_title: Email (Email title override)
website: https://computerstorage.tistory.com
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: yht0827

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  안녕하세요! 3년차 서버 개발자로 주로 Java 언어를 사용하며 <mark>Back-end</mark> 업무를 맡아서 역할을 수행하고 있습니다. 개발을 통해 성취감을 얻는 것을 좋아합니다.
  
  다양한 프로젝트를 통해 유지 보수하기 쉽고, 지속적으로 성장 가능한 소프트웨어에 관심이 많습니다. 때문에 테스트 작성을 중요하게 생각하고 있으며 현재 테스트 코드 도입을 위해 새로운 프로젝트 진행시 테스트 코드 작성을 병행하며 개발하고 있습니다.
  
  꾸준한 노력을 통해 끊임없는 성장해서 동료들, 유저들에게 선한영향력을 미칠수 있는 개발자가 되고 싶습니다.
  
  위에서 언급한 개발자가 되기 위하여 지금도 끊임없이 공부중이고 발전하고 있습니다. 블로그에는 공부를 하면서 알게된점, 고민했던 점을 녹이면서 글을 작성하고 있으며 현재도 발전을 위하여 다양한 개발관련 대외활동을 진행하고 있습니다.

content:
  - title: Work Experience
    layout: list
    content:
      - layout: top-left
        title: Ahnlab
        sub_title: Software Engineer
        caption: 2020.01.06 ~
        description: | # this will include new lines to allow paragraphs
          **Ahnlab AIPS (차세대 네트워크 침입방지 솔루션)**:<a href="https://www.ahnlab.com/kr/site/product/productView.do?prodSeq=131" target="_blank" style="color: inherit;font-style: italic;font-weight: 300;">AIPS</a>
          - <mark>WebSocket</mark>, <mark>stomp</mark>을 활용하여 탐지 경보 기능 개발
          - Snort 정책 파일 업로드(import), 다운로드(export) 기능 개발
          - 외부 보안 인증 서버(LDAPS, RADIUS, TACACS+) 연동 로그인 기능 개발
          - 대용량 로그 분석 및 모니터링 페이지 UI 개선(로그 타입 별 Tab, 검색 방식 개선)
          - 대용량 정책 데이터 처리(bulk insert) 및 <mark>Lucene</mark>을 활용하여 조회 성능 개선
          - 타 장비 연동을 통한 자동 펌웨어 업데이트 시 장비 재시작 오류 이슈 처리  
          - Lucene Index 파일과 DB 데이터 Sync 문제 이슈 처리

  - title: Other Experience
    layout: list
    content:
      - layout: top-left
        title: Toy Project
        description: | # this will include new lines to allow paragraphs
          **ㅊㅊ(이건 어때요? 저건 어때요? 세상 모든 것에 대한 추천을 하는 커뮤니티)**:<a href="https://github.com/f-lab-edu/chu-chu" target="_blank" style="color: inherit;font-style: italic;font-weight: 300;">chu-chu</a>
           -  

          **hot-deal-moa(E-commerce 핫딜 서비스)**:<a href="https://github.com/f-lab-edu/hot-deal-moa" target="_blank" style="color: inherit;font-style: italic;font-weight: 300;">hot-deal-moa</a>
           - 
          
          **자격증 관리 플랫폼(job-search-platform)**:<a href="https://github.com/yht0827/JobSearchPlatform" target="_blank" style="color: inherit;font-style: italic;font-weight: 300;">job-search-platform</a>
          - <mark>HyperLedger</mark> <mark>React</mark> <mark>Redux</mark>
          - HyperLedger Fabric 블록체인 네트워크로 자격증 관리 플랫폼 구축
          - Playground를 활용하여 체인코드 생성(Query, script, acl, model)
          - React를 사용하여 플랫폼 웹 사이트 제작

      - layout: top-left
        title: Certificate
        description: | # this will include new lines to allow paragraphs
          **정보보안기사 (2019. 06. 21)**
          
          **SQLD (2018. 10. 02)**
          
          **정보처리기사 (2017. 11. 24)**
          
          **CSTS (2017. 11. 24)**

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Institution name
        sub_title: Qualifications (eg. BA Performing Arts)
        caption: Date Range (eg. 2016 - 2019)
        quote: >
          Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Description of qualification
more_title: Others
more_content: | # this will include new lines to allow paragraphs
  - 한이음 멘토링 프로젝트 (2019.04 ~ 2019.12)
  - 대학교 성적 우수 과목 멘토링 (2017.03 ~ 2017.12)
  - 3D Print & IoT Camp (2016.05)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude: [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
]
